# Generated by Django 5.1.4 on 2025-02-03 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('date_added', models.DateField()),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/pdfs/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures/')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='eventreaction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='document',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddConstraint(
            model_name='eventreaction',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_reaction'),
        ),
    ]
