# Generated by Django 5.1.4 on 2025-02-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_diary_alter_eventreaction_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreaction',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventreaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.AlterField(
            model_name='diary',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/Y%/M%/d%/'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/Y%/M%/d%/'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='EventReaction',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
