# Generated by Django 5.1.4 on 2025-02-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(choices=[('Semester1', 'Semester 1'), ('Semester2', 'Semester 2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='yearofstudy',
            name='year',
            field=models.CharField(choices=[('Year1', 'Year 1'), ('Year2', 'Year 2'), ('Year3', 'Year 3'), ('Year4', 'Year 4')], max_length=20, verbose_name='Year of Study'),
        ),
    ]
