# Generated by Django 5.1.4 on 2025-01-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='Category',
            new_name='category',
        ),
    ]
