# Generated by Django 5.1.4 on 2025-01-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_room_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
