# Generated by Django 5.1.4 on 2025-02-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_category_slug_thread_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='category',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='thread',
            new_name='reply',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='title',
        ),
        migrations.AddField(
            model_name='thread',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='chats/Y%/M%/d%/'),
        ),
        migrations.AddField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chats/Y%/M%/d%/'),
        ),
        migrations.AddField(
            model_name='thread',
            name='vedio',
            field=models.FileField(blank=True, null=True, upload_to='chats/Y%/M%/d%/'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
