# Generated by Django 5.1.4 on 2025-02-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_thread_category_rename_thread_reply_reply_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='thread',
        ),
    ]
