# Generated by Django 5.1.4 on 2025-02-02 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='user',
        ),
    ]
