# Generated by Django 5.1.4 on 2025-02-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsresult',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
