# Generated by Django 5.1.4 on 2025-01-28 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_owner',
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
