# Generated by Django 5.1.4 on 2025-01-28 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomassignment',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='seminary.room'),
        ),
    ]
